version = "3.8.3"
runner.dialect = scala3

maxColumn = 100
assumeStandardLibraryStripMargin = true
align.stripMargin = true
align.preset = more
rewrite.rules = [
  SortModifiers,
  PreferCurlyFors,
]
rewrite.scala3.convertToNewSyntax = true

fileOverride {
  "glob:**/project/**" {
     runner.dialect = scala213
  }
  "glob:**/*.sbt" {
     runner.dialect = scala213
  }
}

indent.callSite = 2
indent.defnSite = 2
align.openParenCallSite = false
align.openParenDefnSite = false
rewrite.insertBraces.minLines = 1
rewrite.insertBraces.allBlocks = true
newlines.source = unfold